export const generateCyberEmail = (title, message, models) => {
    // Generate rows for the table
    const rows = models.map(m => `
        <tr style="border-bottom: 1px solid #333;">
            <td style="padding: 12px; color: #fff; font-family: 'Courier New', monospace;">${m.name}</td>
            <td style="padding: 12px; text-align: right;">
                <span style="
                    display: inline-block;
                    padding: 4px 12px;
                    border-radius: 4px;
                    background: ${m.success ? 'rgba(0, 255, 0, 0.1)' : 'rgba(255, 0, 0, 0.1)'};
                    border: 1px solid ${m.success ? '#0aff0a' : '#ff2a2a'};
                    color: ${m.success ? '#0aff0a' : '#ff2a2a'};
                    font-weight: bold;
                    font-size: 12px;
                    box-shadow: 0 0 5px ${m.success ? '#0aff0a' : '#ff2a2a'};
                ">
                    ${m.success ? 'ONLINE' : 'OFFLINE'}
                </span>
            </td>
        </tr>
    `).join('');

    return `
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="utf-8">
        <title>${title}</title>
    </head>
    <body style="margin: 0; padding: 0; background-color: #050510; font-family: sans-serif;">
        <div style="max-width: 600px; margin: 0 auto; background-color: #0b0b1e; border: 1px solid #00f3ff; border-radius: 8px; overflow: hidden; margin-top: 20px;">
            
            <!-- Header -->
            <div style="background: linear-gradient(90deg, #050510, #001a1d); padding: 20px; border-bottom: 2px solid #00f3ff; text-align: center;">
                <h1 style="color: #00f3ff; margin: 0; font-family: 'Orbitron', sans-serif; letter-spacing: 2px; text-shadow: 0 0 10px #00f3ff;">GEMINI SENTINEL</h1>
                <p style="color: #666; margin: 5px 0 0 0; font-size: 12px;">AUTOMATED DIAGNOSTIC REPORT</p>
            </div>

            <!-- Body -->
            <div style="padding: 30px; color: #ccc;">
                <h2 style="color: #fff; margin-top: 0;">${title}</h2>
                <p style="line-height: 1.6;">${message}</p>
                
                <table style="width: 100%; border-collapse: collapse; margin-top: 20px; background: rgba(255,255,255,0.02);">
                    ${rows}
                </table>

                <div style="margin-top: 30px; text-align: center;">
                    <a href="http://localhost:3000" style="
                        display: inline-block;
                        padding: 12px 30px;
                        background: transparent;
                        color: #00f3ff;
                        text-decoration: none;
                        border: 1px solid #00f3ff;
                        font-weight: bold;
                        border-radius: 4px;
                        text-transform: uppercase;
                        letter-spacing: 1px;
                    ">
                        OPEN DASHBOARD
                    </a>
                </div>
            </div>

            <!-- Footer -->
            <div style="background-color: #050510; padding: 15px; text-align: center; color: #444; font-size: 12px; border-top: 1px solid #333;">
                GENERATED BY GEMINI SENTINEL AI MONITOR<br>
                ${new Date().toISOString()}
            </div>
        </div>
    </body>
    </html>
    `;
};
